# Generated by Django 5.2.6 on 2025-11-16 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='negative',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='positive',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='price',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='score',
            field=models.FloatField(default=0.0),
        ),
    ]
