# Generated by Django 5.2.7 on 2025-11-17 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_game_negative_game_positive_game_price_game_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.IntegerField()),
                ('game_name', models.CharField(max_length=255)),
                ('cover_image', models.URLField(blank=True, null=True)),
                ('genre', models.CharField(blank=True, max_length=100)),
                ('year', models.CharField(blank=True, max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.users')),
            ],
        ),
        migrations.CreateModel(
            name='PlayedGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.IntegerField()),
                ('game_name', models.CharField(max_length=255)),
                ('cover_image', models.URLField(blank=True, null=True)),
                ('genre', models.CharField(blank=True, max_length=100)),
                ('year', models.CharField(blank=True, max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.users')),
            ],
        ),
    ]
