# Generated by Django 5.2.7 on 2025-11-16 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='release_date',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='game',
            name='screenshots',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
