# Generated by Django 5.2.7 on 2025-11-17 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_favoritegame_playedgame'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritegame',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='favoritegame',
            name='game_name',
        ),
        migrations.RemoveField(
            model_name='playedgame',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='playedgame',
            name='game_name',
        ),
        migrations.AddField(
            model_name='favoritegame',
            name='cover',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='favoritegame',
            name='title',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playedgame',
            name='cover',
            field=models.CharField(default='default.jpg', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playedgame',
            name='title',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='favoritegame',
            name='game_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='favoritegame',
            name='genre',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='favoritegame',
            name='year',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='playedgame',
            name='game_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='playedgame',
            name='genre',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='playedgame',
            name='year',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
