# Generated by Django 5.2.7 on 2025-11-16 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_game_release_date_game_screenshots'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='detailed_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
