# Generated by Django 4.2.26 on 2025-12-02 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_favoritegame_cover_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='role',
            field=models.CharField(default='user', max_length=20),
        ),
    ]
