# Generated by Django 5.2.7 on 2025-11-16 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_game_detailed_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='genre',
            field=models.CharField(blank=True, default='Unknown', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='release_date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
