# Generated by Django 5.2.8 on 2025-12-04 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_favoritegame_cover_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_public', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_lists', to='main.users')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='CustomListGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('cover', models.CharField(max_length=500)),
                ('genre', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.CharField(blank=True, max_length=20, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('custom_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='main.customlist')),
            ],
            options={
                'ordering': ['-added_at'],
                'unique_together': {('custom_list', 'game_id')},
            },
        ),
    ]
