# Generated by Django 4.2.26 on 2025-12-02 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_users_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='otp_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='otp_valid_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
