# Generated by Django 4.2.26 on 2025-12-02 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_users_otp_code_users_otp_valid_until'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='otp_code',
        ),
        migrations.RemoveField(
            model_name='users',
            name='otp_valid_until',
        ),
        migrations.AddField(
            model_name='users',
            name='totp_secret',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
