# Generated by Django 4.2.26 on 2025-12-02 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_users_otp_code_remove_users_otp_valid_until_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='totp_verified',
            field=models.BooleanField(default=False),
        ),
    ]
